from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional
from datetime import datetime
from models import AutomationPotential

class ValueChainStageBase(BaseModel):
    name: str = Field(description="Name of the value chain stage")
    description: str = Field(description="Short description of the stage")

class ValueChainStageCreate(ValueChainStageBase):
    sequence_order: int

class ValueChainStage(ValueChainStageBase):
    id: int
    industry_id: int
    sequence_order: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)

class ProcessBase(BaseModel):
    name: str = Field(description="Name of the real-world process")
    business_purpose: str = Field(description="The primary business purpose of this process")

class ProcessCreate(ProcessBase):
    pass

class Process(ProcessBase):
    id: int
    stage_id: int
    created_at: datetime
    model_config = ConfigDict(from_attributes=True)

class ProcessFindingBase(BaseModel):
    current_challenges: str = Field(description="Current challenges faced in this process")
    ai_opportunity: str = Field(description="Description of the AI opportunity")
    relevant_ai_capabilities: str = Field(description="Relevant AI capabilities (e.g. Computer Vision, Generative AI)")
    potential_benefit: str = Field(description="Potential business benefit of applying AI")
    risk: str = Field(description="Risks associated with this AI application")
    automation_potential: AutomationPotential = Field(description="Potential for automation (low, medium, high)")
    confidence_score: float = Field(description="Confidence score derived from evidence")

class ProcessFindingCreate(ProcessFindingBase):
    pass

class ProcessFinding(ProcessFindingBase):
    id: int
    process_id: int
    model_config = ConfigDict(from_attributes=True)

class EvidenceSourceBase(BaseModel):
    source_url: str = Field(description="URL of the source")
    source_title: str = Field(description="Title of the source")
    extracted_snippet: str = Field(description="The exact text snippet that supports the claim")

class EvidenceSourceCreate(EvidenceSourceBase):
    pass

class EvidenceSource(EvidenceSourceBase):
    id: int
    process_id: int
    supports_finding_id: Optional[int] = None
    retrieved_at: datetime
    model_config = ConfigDict(from_attributes=True)

class PriorityScoreBase(BaseModel):
    business_impact_score: float = Field(ge=0, le=10)
    feasibility_score: float = Field(ge=0, le=10)
    risk_score: float = Field(ge=0, le=10)
    evidence_confidence: float = Field(ge=0, le=10)
    final_priority_score: float
    rank: Optional[int] = None

class PriorityScoreCreate(PriorityScoreBase):
    pass

class PriorityScore(PriorityScoreBase):
    id: int
    process_id: int
    computed_at: datetime
    model_config = ConfigDict(from_attributes=True)

class IndustryBase(BaseModel):
    name: str

class IndustryCreate(IndustryBase):
    pass

class Industry(IndustryBase):
    id: int
    created_at: datetime
    last_analyzed_at: Optional[datetime] = None
    model_config = ConfigDict(from_attributes=True)

class LLMValueChainStageList(BaseModel):
    stages: List[ValueChainStageBase]

class LLMProcessList(BaseModel):
    processes: List[ProcessBase]

class LLMProcessAnalysis(BaseModel):
    findings: ProcessFindingBase
    # evidence sources are not generated by LLM, they are provided, but the LLM maps claims to evidence.
    # To keep it simple as per instructions, LLM outputs the finding.
